"""Turning a mail body into something a terminal can actually show.

Two entry points, one job between them: given a `Message`, produce text a
person can read at 80 columns.

`clean_plain_text` exists because a `text/plain` part is not the same thing as
readable text. Most bulk mail is authored as HTML and the plain half is
generated by flattening it, which leaves wreckage a mail *reader* is expected
to hide:

    <!--[if !mso]><!-->            conditional-comment markers, verbatim
    <!--[if mso]> …VML… <![endif]--> the whole Outlook-only branch, verbatim
    …the same paragraph twice       once per branch of that conditional
    <https://c.gle/ACT4x…160 more…>Edmingle   the href glued to its anchor

A Google account notification arrives with thirty-odd lines of that, and it is
why such a message is unreadable here while looking fine in a browser.

`html_to_text` is the fallback for mail that ships no plain part at all. It is
a flattener, not a renderer: it has no layout, so a table becomes one line per
cell. What it does care about is the things that make the difference between
prose and rubble — collapsing source whitespace so sentences are not broken at
the author's line endings, keeping cells apart, dropping the hidden preheader
that would otherwise be the first thing you read, and not silently discarding
every link in a message whose entire content is links.

Both funnel long URLs into a numbered list at the end. A 400-character tracking
URL in the middle of a paragraph destroys the paragraph; `ui/render.py`
hyperlinks whatever survives, so a footnote is still one click.
"""

from __future__ import annotations

import re
from functools import lru_cache
from html.parser import HTMLParser

from rich.text import Text

from .models import Message

# A URL up to this long reads as part of the sentence. Past it, the URL *is*
# the line, so it moves to the footnotes and leaves a marker behind.
INLINE_URL_MAX = 60

# Alt text longer than this is a description of an image, not a caption for it.
ALT_TEXT_MAX = 80

# Zero-width and invisible characters. Bulk mail pads preheaders with runs of
# these to control what the inbox preview shows; they arrive as blank-looking
# lines that are not blank, which defeats every "collapse empty lines" rule.
_INVISIBLE_RE = re.compile("[\u200b-\u200f\u2060\ufeff\u034f\u00ad]")
_THIN_SPACE_RE = re.compile("[\u00a0\u2000-\u200a\u202f\u205f\u3000]")
_LINE_SEP_RE = re.compile("[\u2028\u2029]")


class _Links:
    """Numbered link footnotes, deduplicated by target."""

    def __init__(self) -> None:
        self.urls: list[str] = []
        self._seen: dict[str, int] = {}

    def ref(self, url: str) -> str:
        """A marker to leave in the text: the URL itself, or ``[3]``."""
        url = url.strip()
        if len(url) <= INLINE_URL_MAX:
            return url
        number = self._seen.get(url)
        if number is None:
            self.urls.append(url)
            number = self._seen[url] = len(self.urls)
        return f"[{number}]"

    def section(self) -> str:
        if not self.urls:
            return ""
        lines = ["", "Links"]
        lines.extend(f"[{i}] {url}" for i, url in enumerate(self.urls, 1))
        return "\n".join(lines)


# -- plain text ---------------------------------------------------------------

# Downlevel-*revealed* conditionals: the markers are comments but the content
# between them is real, so the markers go and the content stays. These must be
# removed before the hidden form below, or its non-greedy match would run from
# one of these openers to the next `<![endif]-->` and eat the message.
_COND_REVEAL_RE = re.compile(r"<!--\[if\b[^\]]*\]>\s*<!-->|<!--\s*<!\[endif\]-->")
# Downlevel-hidden: opener, content, closer — all of it Outlook-only.
_COND_HIDDEN_RE = re.compile(r"<!--\[if\b[^\]]*\]>.*?<!\[endif\]-->", re.DOTALL)
_COND_ORPHAN_RE = re.compile(r"<!\[endif\]-->|<!--\[if\b[^\]]*\]>")
_COND_ANY_RE = re.compile(r"<!--\[if\b|<!\[endif\]-->")


def looks_flattened(text: str) -> bool:
    """Was this `text/plain` part generated by flattening an HTML body?

    Conditional-comment markers in a plain-text part cannot be anything else:
    nothing writing prose types `<!--[if mso]>`. It is the one reliable signal
    that the part is a by-product rather than the message.
    """
    return bool(_COND_ANY_RE.search(text))

# `<url>` optionally glued straight onto its anchor text, which is how a
# flattened `<a>` arrives: `<https://…>Edmingle`.
_BRACKETED_URL_RE = re.compile(r"<(https?://[^\s>]+)>(\S*)")
# A bare URL, with trailing sentence punctuation left out of the match.
_BARE_URL_RE = re.compile(r"(?<![\w@<])(https?://[^\s<>\"'`]+[^\s<>\"'`.,;:!?)\]])")

# Lines that must never be joined onto the one above: quotes and list items.
_NO_JOIN_RE = re.compile(r"^\s*([>*•·+-]\s|\d{1,3}[.)]\s)")
# A line with no letter or digit in it is a rule or a signature delimiter --
# `-- ` ends in a space like a soft break does, and joining it to the name
# below would eat the delimiter every plain-text signature is recognised by.
_WORDLESS_RE = re.compile(r"^[^\w]*$")


def clean_plain_text(text: str, links: _Links | None = None) -> str:
    """Make a `text/plain` part fit to print."""
    own_links = links is None
    links = links or _Links()

    text = text.replace("\r\n", "\n").replace("\r", "\n")
    text = _LINE_SEP_RE.sub("\n", text)
    text = _INVISIBLE_RE.sub("", text)
    text = _THIN_SPACE_RE.sub(" ", text)

    stripped = _COND_REVEAL_RE.sub("", text)
    stripped = _COND_HIDDEN_RE.sub("", stripped)
    stripped = _COND_ORPHAN_RE.sub("", stripped)
    # The residue is the tell that this part was machine-flattened out of an
    # HTML body, which is the only case where wholesale block deduplication
    # below is safe to apply.
    flattened = stripped != text
    text = stripped

    text = _unwrap_soft_breaks(text)
    text = _footnote_urls(text, links)
    if flattened:
        text = _drop_repeated_blocks(text)
    text = _tidy_blank_lines(text)

    if own_links:
        text = (text + "\n" + links.section()).rstrip() if links.urls else text
    return text


def _unwrap_soft_breaks(text: str) -> str:
    """Rejoin lines the sender hard-wrapped for a 78-column window.

    A trailing space before the newline is the soft-break convention (RFC 3676
    format=flowed, and what Google's flattener emits — two of them). Honouring
    it lets the reader wrap to the width it actually has instead of showing
    someone else's ragged margin folded again at ours.
    """
    lines = text.split("\n")
    out: list[str] = []
    for line in lines:
        if (
            out
            and out[-1].endswith(" ")
            and out[-1].strip()
            and not _WORDLESS_RE.match(out[-1])
            and line.strip()
            and not _NO_JOIN_RE.match(line)
            and not out[-1].lstrip().startswith(">")
        ):
            out[-1] = out[-1].rstrip() + " " + line.lstrip()
        else:
            out.append(line)
    return "\n".join(out)


def _footnote_urls(text: str, links: _Links) -> str:
    def bracketed(match: re.Match[str]) -> str:
        url, glued = match.group(1), match.group(2)
        ref = links.ref(url)
        if not glued:
            return ref
        # The flattener writes the href first and the anchor text after it;
        # a reader wants them the other way round.
        return f"{glued} {ref}" if ref.startswith("[") else f"{glued} ({ref})"

    text = _BRACKETED_URL_RE.sub(bracketed, text)
    text = _BARE_URL_RE.sub(lambda m: links.ref(m.group(1)), text)
    # A URL the sender had already wrapped in brackets leaves them around the
    # marker that replaced it -- `Save now ( [2] )`, sometimes with the newlines
    # of the original layout still in between.
    return re.sub(r"[(<]\s*(\[\d+\])\s*[)>]", r"\1", text)


def _drop_repeated_blocks(text: str) -> str:
    """Drop paragraphs that already appeared earlier, when they repeat in runs.

    Only ever called on a body that carried conditional-comment residue. Such a
    body holds two branches of the same content flattened one after the other,
    so whole *sequences* of paragraphs arrive twice; a human-written message is
    never put through this.

    The run requirement is what keeps it honest. A paragraph is dropped only
    when the paragraph beside it repeats in the same order too — otherwise a
    line that genuinely appears twice, like an address given once in the header
    and once again as the value under "Email address", would be silently lost
    the second time and leave its label standing alone.
    """
    blocks = re.split(r"\n\s*\n", text)
    keys = [" ".join(block.split()).casefold() for block in blocks]
    earlier: dict[str, list[int]] = {}
    kept: list[str] = []
    for i, key in enumerate(keys):
        seen = earlier.get(key, [])
        repeats_in_run = any(
            (i + 1 < len(keys) and j + 1 < i and keys[i + 1] == keys[j + 1])
            or (i and j and keys[i - 1] == keys[j - 1])
            for j in seen
        )
        if key and not repeats_in_run:
            kept.append(blocks[i])
        earlier.setdefault(key, []).append(i)
    return "\n\n".join(kept)


def _tidy_blank_lines(text: str) -> str:
    """Right-strip every line, then collapse runs of blank ones.

    The right-strip is what makes the collapse work: a "blank" line out of a
    layout table is usually a line holding one space, and `\\n{3,}` does not
    match those.
    """
    text = "\n".join(line.rstrip() for line in text.split("\n"))
    return re.sub(r"\n{3,}", "\n\n", text).strip()


# -- HTML ---------------------------------------------------------------------

_VOID_TAGS = {
    "area", "base", "br", "col", "embed", "hr", "img", "input", "link",
    "meta", "param", "source", "track", "wbr",
}
# Content of these is markup, metadata, or a fallback for readers that cannot
# do what we are doing here. `<title>` is inside `<head>`: dropping the head
# whole is what stops the subject appearing twice.
_SKIP_TAGS = {
    "head", "script", "style", "noscript", "template", "svg", "math",
    "object", "iframe", "select", "textarea",
}
# A blank line before and after.
_PARAGRAPH_TAGS = {
    "p", "table", "blockquote", "pre", "h1", "h2", "h3", "h4", "h5", "h6",
    "ul", "ol", "dl", "section", "article", "header", "footer", "aside",
    "figure", "form", "hr", "address", "fieldset",
}
# A line of their own. `td` matters most: without it every cell of a layout
# table runs into the next one — "Snehangshu BhuinName and profile picture".
_LINE_TAGS = {"div", "tr", "td", "th", "li", "dt", "dd", "center", "caption"}

_HIDDEN_STYLE_RE = re.compile(
    r"(display\s*:\s*none|visibility\s*:\s*hidden|mso-hide\s*:\s*all"
    r"|font-size\s*:\s*0|max-height\s*:\s*0)",
    re.IGNORECASE,
)
_FILENAME_ALT_RE = re.compile(r"\.(png|jpe?g|gif|webp|svg)\b", re.IGNORECASE)


class _Flattener(HTMLParser):
    def __init__(self, links: _Links) -> None:
        super().__init__(convert_charrefs=True)
        self.links = links
        self._lines: list[str] = []
        self._buf: list[str] = []
        self._pending = 0          # 0 none, 1 line break, 2 blank line
        self._open: list[str] = []  # open elements, for subtree skipping
        self._skips: list[int] = []  # depths at which a skipped subtree began
        self._lists: list[int | None] = []
        self._href: str | None = None
        self._anchor_text: list[str] = []
        self._pre = 0

    # -- assembly --

    def _emit(self, chunk: str) -> None:
        if self._pending:
            self._flush()
        if not self._buf:
            chunk = chunk.lstrip()
        if chunk:
            self._buf.append(chunk)

    def _flush(self) -> None:
        line = "".join(self._buf).rstrip()
        if not self._pre:
            # Cell and span boundaries each contribute a space; two of them
            # meeting mid-sentence should still read as one.
            line = re.sub(r"(?<=\S) {2,}", " ", line)
        self._buf = []
        if line or self._pending < 2:
            self._lines.append(line)
        if self._pending >= 2 and self._lines and self._lines[-1]:
            self._lines.append("")
        self._pending = 0

    def _break(self, level: int) -> None:
        if self._buf or self._lines:
            self._pending = max(self._pending, level)

    def text(self) -> str:
        self._pending = max(self._pending, 1)
        self._flush()
        return _tidy_blank_lines("\n".join(self._lines))

    # -- parser hooks --

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        tag = tag.lower()
        void = tag in _VOID_TAGS
        if not void:
            self._open.append(tag)
        if self._skips:
            return
        if not void and (tag in _SKIP_TAGS or _is_hidden(attrs)):
            self._skips.append(len(self._open) - 1)
            return
        self._start(tag, dict((k.lower(), v or "") for k, v in attrs))

    def handle_startendtag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        if self._skips:
            return
        self._start(tag.lower(), dict((k.lower(), v or "") for k, v in attrs))

    def _start(self, tag: str, attrs: dict[str, str]) -> None:
        if tag == "br":
            self._break(1)
        elif tag == "hr":
            self._break(2)
            self._emit("─" * 24)
            self._break(2)
        elif tag == "img":
            self._image(attrs)
        elif tag == "a":
            self._href = (attrs.get("href") or "").strip()
            self._anchor_text = []
        elif tag in ("ul", "ol"):
            self._break(2)
            self._lists.append(1 if tag == "ol" else None)
        elif tag == "li":
            self._break(1)
            depth = max(len(self._lists) - 1, 0)
            marker = "•"
            if self._lists and self._lists[-1] is not None:
                marker = f"{self._lists[-1]}."
                self._lists[-1] += 1
            self._emit("  " * depth + marker + " ")
        elif tag == "pre":
            self._pre += 1
            self._break(2)
        elif tag in _PARAGRAPH_TAGS:
            self._break(2)
        elif tag in _LINE_TAGS:
            self._break(1)

    def handle_endtag(self, tag: str) -> None:
        tag = tag.lower()
        if tag in _VOID_TAGS:
            return
        if tag in self._open:
            while self._open:
                popped = self._open.pop()
                while self._skips and self._skips[-1] >= len(self._open):
                    self._skips.pop()
                if popped == tag:
                    break
        if self._skips:
            return
        if tag == "a":
            self._close_anchor()
        elif tag in ("ul", "ol"):
            if self._lists:
                self._lists.pop()
            self._break(2)
        elif tag == "pre":
            self._pre = max(self._pre - 1, 0)
            self._break(2)
        elif tag in _PARAGRAPH_TAGS:
            self._break(2)
        elif tag in _LINE_TAGS:
            self._break(1)

    def handle_data(self, data: str) -> None:
        if self._skips or not data:
            return
        if self._pre:
            for i, line in enumerate(data.split("\n")):
                if i:
                    self._break(1)
                self._emit(line)
            return
        data = _THIN_SPACE_RE.sub(" ", _INVISIBLE_RE.sub("", data))
        # Collapsing source newlines is the point: without it a paragraph laid
        # out over five lines of HTML source stays broken at those five points
        # no matter how wide the terminal is.
        chunk = re.sub(r"\s+", " ", data)
        if not chunk.strip() and not self._buf:
            return
        if self._href is not None:
            self._anchor_text.append(chunk)
        self._emit(chunk)

    # -- pieces --

    def _image(self, attrs: dict[str, str]) -> None:
        alt = " ".join((attrs.get("alt") or "").split())
        if not alt or len(alt) > ALT_TEXT_MAX or _FILENAME_ALT_RE.search(alt):
            return
        if attrs.get("width") in ("0", "1") or attrs.get("height") in ("0", "1"):
            return  # a tracking pixel, whatever it calls itself
        if self._href is not None:
            self._anchor_text.append(alt)
        self._emit(alt + " ")

    def _close_anchor(self) -> None:
        href, self._href = self._href, None
        text = " ".join("".join(self._anchor_text).split())
        self._anchor_text = []
        if not href or href.startswith(("#", "javascript:", "cid:", "data:")):
            return
        target = href[7:] if href.lower().startswith("mailto:") else href
        if not text:
            # An image-only link — the target is all there is to show.
            self._emit(self.links.ref(target))
            return
        if _same_target(text, target):
            return
        ref = self.links.ref(target)
        self._emit(f" {ref}" if ref.startswith("[") else f" ({ref})")


def _same_target(text: str, target: str) -> bool:
    """Would the reference just restate the link text?

    Compared whole, never as a substring: an "unsubscribe" link points at a URL
    with `/unsubscribe/` in the path, and a substring test throws that link
    away for looking like its own label.
    """
    def bare(value: str) -> str:
        value = value.strip().rstrip("/").casefold()
        for scheme in ("https://", "http://", "mailto:"):
            if value.startswith(scheme):
                value = value[len(scheme) :]
        return value.removeprefix("www.")

    return bare(text) == bare(target)


def _is_hidden(attrs: list[tuple[str, str | None]]) -> bool:
    """Is this the preheader — the line written to be read only by an inbox?"""
    for key, value in attrs:
        key = key.lower()
        if key == "hidden":
            return True
        if key == "style" and value and _HIDDEN_STYLE_RE.search(value):
            return True
    return False


def html_to_text(html: str, links: _Links | None = None) -> str:
    """Flatten an HTML body into readable plain text."""
    own_links = links is None
    links = links or _Links()
    parser = _Flattener(links)
    try:
        parser.feed(html)
        parser.close()
    except Exception:  # a malformed body is still worth whatever parsed
        pass
    text = parser.text()
    if own_links and links.urls:
        text = (text + "\n" + links.section()).rstrip()
    return text


# -- making it clickable ------------------------------------------------------

# Deliberately conservative: trailing punctuation is far more often sentence
# punctuation than part of the URL.
_URL_RE = re.compile(r"""https?://[^\s<>"'`\]\)]+[^\s<>"'`\]\).,;:!?]""")
# A footnote line as `_Links.section` writes it: `[3] https://…`.
_FOOTNOTE_RE = re.compile(r"^\[(\d+)\]\s+(\S+)$", re.MULTILINE)
# The marker left behind in the prose, wherever it ended up.
_MARKER_RE = re.compile(r"\[\d+\]")


def footnote_targets(text: str) -> dict[str, str]:
    """Map `[3]` back to the address listed for it at the end of the body.

    The markers are the only trace a long URL leaves in the sentence it came
    from, so they have to be clickable too, or footnoting a link would have
    cost the reader the click it used to have.
    """
    return {f"[{n}]": url for n, url in _FOOTNOTE_RE.findall(text)}


def linkify(text: Text, targets: dict[str, str] | None = None) -> Text:
    """Turn URLs, and any footnote markers, into OSC 8 hyperlinks.

    Styling before wrapping is what makes this survive a URL that gets folded
    across two lines — `Text.wrap` carries the style onto both halves, so both
    remain clickable and both point at the whole address.
    """
    for match in _URL_RE.finditer(text.plain):
        text.stylize(f"link {match.group(0)}", match.start(), match.end())
    for match in _MARKER_RE.finditer(text.plain) if targets else ():
        url = targets.get(match.group(0))
        if url:
            text.stylize(f"link {url}", match.start(), match.end())
    return text


# -- choosing between them ----------------------------------------------------


# The UI re-renders the reader on every frame, so a 60 KB HTML body would be
# reparsed on each keystroke. Bodies are immutable and the same `str` object
# comes back each time, so memoizing the two conversions costs one dict lookup.
@lru_cache(maxsize=16)
def _plain(text: str) -> str:
    return clean_plain_text(text)


@lru_cache(maxsize=16)
def _flattened(html: str) -> str:
    return html_to_text(html)


def message_body(msg: Message, *, prefer_html: bool = False) -> str | None:
    """The body to show, cleaned. `None` when the message has neither part.

    `prefer_html` is `gmail read --html`, which wants the source itself.
    """
    if prefer_html and msg.body_html:
        return msg.body_html
    if msg.body_text and msg.body_text.strip():
        # A flattened plain part is a by-product, and a poor one: it keeps the
        # branches of the conditional it could not evaluate, and it breaks
        # sentences wherever the HTML had a tag. When the HTML it came from is
        # right there, flattening that ourselves reads better -- but only if
        # something actually comes out of it.
        if looks_flattened(msg.body_text) and msg.body_html:
            from_html = _flattened(msg.body_html)
            if from_html.strip():
                return from_html
        return _plain(msg.body_text)
    if msg.body_html:
        return _flattened(msg.body_html)
    return None
